language: node_js
node_js:
  - "7"
env:
  BUILDKITE_DOCKER: false

steps:
  - command: "yarn run test"
    agents:
      - "queue=elastic"

  - wait

  - command: "yarn run build"
    agents:
      - "queue=elastic"
