# language: node_js
# node_js:
#   - "7"

steps:
  - command: "yarn install && yarn run test"
    agents:
      - "queue=default"

  - wait

  - command: "yarn run build"
    agents:
      - "queue=default"
