language: node_js
node_js:
  - "7"
# env:
#   BUILDKITE_DOCKER: false

steps:
  - command: yarn install && yarn run test
    plugins:
      docker#v1.0.0:
        image: "node:7"
        workdir: /app
        agents:
          - "queue=elastic"

  - wait

  # - command: "yarn run test"
    # agents:
    #   - "queue=elastic"

  - wait

  - command: "yarn run build"
    agents:
      - "queue=elastic"
